#
# Sera - OnePage Jekyll Theme
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "README.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
url: "https://www.cleemedical.com"
baseurl: ""

####################################
######   Optional Features    ######
####################################
smooth-scroll: true 

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Clee Medical SA
# Website language
lang: en-US
# Header Title
header-title: <strong>Forging a new era of highly targeted neuro therapies</strong>
# Header Tagline
headter-tagline: 

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Follow us
  url: https://www.linkedin.com/company/clee-medical/

# Secondary Buttons
header-secondary-button:
  title: Contact us
  url: https://www.cleemedical.com/#contact

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: jules.scholler@cleemedical.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://cleemedical.com

####################################
######  Global Social Links   ######
####################################
youtube: "#"
pinterest: "#"
facebook: "#"
twitter: "#"
google-plus: "#"
vimeo: "#"
linkedin : "https://www.linkedin.com/company/clee-medical"

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: team.jpg
  author-name: Clee Medical
  author-tagline: Blog Author
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
  author-social-links:
    linkedin: "https://www.linkedin.com/company/clee-medical"

# Google Map JS api
key-api: YOUR_GOOGLE_MAP_API_KEY
map-text: Sera Google Map
map-lat: 46.22204203038014
map-lng: 6.148248685831963

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Theme created by Ohkimur
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Vision
about-description: Our vision is to redefine the boundaries of neuroscience with minimally invasive technologies to enable unparalleled precision, enhance patient outcomes, and forge a new era of highly targeted neurotherapies for a healthier world.
#####################################
#############  Features  ############
#####################################
# features-title: Features
# features-description: Neuro Access integrates innovative imaging and sensing technology to provide unparalleled access, vision and navigation within the brain. Neuro Access works alongside existing neurosurgical equipment and can be easily incorporated into current surgical routines.
# #
# # Features
# #
# features:
#   # Feature
#   - title: Precise
#     description: 200x times better resolution than cutting edge MRI.
#     icon: pe-7s-vector

#   # Feature
#   - title: Enables
#     description: All stereotactic & functional neurosurgeries.
#     icon: pe-7s-help2

#   # Feature
#   - title: Safety
#     description: Real time guidance through machine learning and AI.
#     icon: pe-7s-airplay

#####################################
############  Portfolio  ############
#####################################
portfolio-title:
portfolio-description: "Brain surgery traditionally relies on pre-operative MRI imaging, which often falls short in enabling precise targeting during procedures. At Clee Medical, we’ve developed a groundbreaking solution: real-time, ultra-high-resolution brain visualization during surgery—live, without the need for contrast agents or radiation. We are setting a new standard in neuroimaging, seamlessly bridging the gap between preoperative diagnostics and real-time surgical precision."


#Portfolio Grid

portfolio-categories:
 [H&E, 3T, OCT, Development, Video, Photography]

portfolio:
  # Portfolio Item
  - title: Histology
    categories: [H&E]
    image: img-01.jpg
    url: "https://www.cleemedical.com/news/2024/12/10/our-technology.html"

  # Portfolio Item
  - title: MRI
    categories: [3T]
    image: img-02.jpg
    url: "https://www.cleemedical.com/news/2024/12/10/our-technology.html"

  # Portfolio Item
  - title: Clee Imaging
    categories: [OCT]
    image: img-03.jpg
    url: "https://www.cleemedical.com/news/2024/12/10/our-technology.html"

#   # Portfolio Item
#   - title: S<span class="thin">era</span> Style
#     categories: [Websites, Video, Photography]
#     image: img-04.jpg
#     url: "#"

#   # Portfolio Item
#   - title: S<span class="thin">era</span> Style
#     categories: [Development, Logo]
#     image: img-05.jpg
#     url: "#"

#   # Portfolio Item
#   - title: S<span class="thin">era</span> Style
#     categories: [Development, Video]
#     image: img-06.jpg
#     url: "#"

#   # Portfolio Item
#   - title: S<span class="thin">era</span> Style
#     categories: [Websites, Graphic Design]
#     image: img-07.jpg
#     url: "#"

#   # Portfolio Item
#   - title: S<span class="thin">era</span> Style
#     categories: [Websites, Video]
#     image: img-08.jpg
#     url: "#"

  # Portfolio Item
  # - title: S<span class="thin">era</span> Style
  #   categories: [Photography, Logo]
  #   image: img-09.jpg
  #   url: "#"

#####################################
##########  Core Features  ##########
#####################################
core-title: Technology
core-description: We are currently developing an innovative imaging and sensing technology to provide unparalleled access, vision and navigation within the brain. It works alongside existing neurosurgical equipment and can be easily incorporated into current surgical routines.

#
# Core Features Left
#
core-features-left:
  # Feature
  - name: Real-time
    description: Blood vessel and tissue detection.
    icon: pe-7s-display1

  # Feature
  - name: Ultra-high resolution
    description: 20 micrometers - 125,000 more voxels per unit volume than MRI.
    icon: pe-7s-look

  # Feature
  - name: Safety
    description: Real time guidance through machine learning and AI.
    icon: pe-7s-shield

  # Feature
  - name: Accuracy
    description: Reach any brain target with unprecedent precision.
    icon: pe-7s-map-marker

#
# Core Features Right
#
core-features-right:
  # Feature
  - name: Enables
    description: All stereotactic & functional neurosurgeries.
    icon: pe-7s-smile

  # Feature
  - name: Empowers
    description: Fill the intraoperative imaging gap.
    icon: pe-7s-map-2

  # Feature
  - name: Innovative
    description: Disposable endoscopic probe, compatible with existing neurosurgical workflows.
    icon: pe-7s-science

  # Feature
  - name: Quality
    description: Engineered and built in Switzerland.
    icon: pe-7s-diamond

#####################################
########### Testimonials ############
#####################################
#testimonials-title: Partners
#testimonials-description:

#
# Testimonials
#
# testimonials:
#   # Client
#   - name: Wyss Center
#     url: https://wysscenter.ch
#     url-text: wysscenter
#     avatar: wyss.jpg
#     cite:
#     logo-img: wyss.jpg

#   # Client
#   - name: FONGIT
#     url: https://wysscenter.ch
#     url-text: fongit
#     avatar: fongit.png
#     cite:
#     logo-img: wyss.png

#   # Client
#   - name: Innosuisse
#     url: https://wysscenter.ch
#     url-text: innosuisse
#     avatar: innosuisse.png
#     cite:
#     logo-img: innosuisse.png

#   # Client
#   - name: Bern University of Applied Sciences
#     url: https://wysscenter.ch
#     url-text: bfh
#     avatar: bfh.png
#     cite:
#     logo-img: bfh.png

#   # Client
#   - name: Venture Kick
#     url: https://wysscenter.ch
#     url-text: venturekick
#     avatar: venturekick.png
#     cite:
#     logo-img: venturekick.png

#################################
########### Partners ############
#################################
partners-title: Partners
partners-description:


#####################################
############# Our Blog ##############
#####################################
blog-title: News
blog-description:

#####################################
############### Team ################
#####################################
team-title: Meet Our Team
team-description:

#
# Team Members
#
team:
  # Team Member
  - name: Matthew Lapinski
    tagline: Co-founder and CEO
    avatar: matt.jpg

    # Social Links
    linkedin: "https://www.linkedin.com/in/matt-lapinski/"


  # Team Member
  - name: Abed Hammoud
    tagline: Co-founder and CTO
    avatar: abed-hammoud.jpg

    # Social Links
    linkedin: "https://www.linkedin.com/in/dr-abed-hammoud/"

  # Team Member
  - name: Jules Scholler
    tagline: Optical Systems Engineer
    avatar: jules.jpg

    # Social Links
    linkedin: "https://www.linkedin.com/in/jules-scholler-17347790/"

  # Team Member
  - name: Gary Evans
    tagline: Principal Engineer
    avatar: gary.jpg

    # Social Links
    linkedin: "https://www.linkedin.com/in/gary-evans-bab171a3/"

  # Team Member
  - name: David Segar
    tagline: Founding advisor, acting CMO<br> Functional neurosurgeon
    avatar: Dave.jpg

    # Social Links
    linkedin: "https://www.linkedin.com/in/david-segar/"

  # Team Member
  - name: Joe Betts-LaCroix
    tagline: Founding advisor<br> CEO of Retro Biosciences
    avatar: Joe.jpg

    # Social Links
    linkedin: "https://www.linkedin.com/in/bettslacroix/"

  # Team Member
  - name: Sam Rodrigues
    tagline: Founding advisor<br> CEO of FutureHouse
    avatar: Sam.jpg

    # Social Links
    linkedin: "https://www.linkedin.com/in/samuel-g-rodriques-080a9b22/"

  # Team Member
  - name: Mat Stratton
    tagline: Advisor<br> Principal of COALITION
    avatar: Mat.jpg

    # Social Links
    linkedin: "https://www.linkedin.com/in/mat-stratton-a6269317/"



#####################################
########## Pricing Tables ###########
#####################################
# pricing-title: Pricing Tables
# pricing-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

# #
# # Plan Personal
# #
# plan-personal-price: $99
# plan-personal-offer-1-title: 01 PSD Pack
# plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-personal-offer-2-title: 100 Support Tickets
# plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-personal-url: "#"

# #
# # Plan Business
# #
# plan-business-price: $499
# plan-business-offer-1-title: 05 PSD Pack
# plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-business-offer-2-title: 1000 Support Tickets
# plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-business-url: "#"

# #
# # Plan Ultimate
# #
# plan-ultimate-price: $999
# plan-ultimate-offer-1-title: 10 PSD Pack
# plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-ultimate-offer-2-title: Support Unlimited
# plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-ultimate-url: "#"

#####################################
############   Contact   ############
#####################################
contact-title: Contact Us
contact-description: Please fill the form below and we will get back to you shortly.

#####################################
#############   Footer   ############
#####################################
footer-description: Forging a new era of highly targeted neuro therapies.
footer-copyright-year: 2024
